name: Bug Report
description: バグレポートはこちらから
labels: ["Priority: High / 優先度：高", "Type: Bug / タイプ：バグ"]

title: "Bug: "
body:
  - type: checkboxes
    id: would-you-tackle-this-issue
    attributes:
      label: Would you tackle this Issue?
      description: この Issue にあなたが取り組みますか？
      options:
        - label: Yes, it would.

  - type: checkboxes
    id: have-you-viewed-readme
    attributes:
      label: Have you viewed README.md?
      description: "[README.md](https://github.com/aonekoaoi/aonekoaoi.github.io/blob/main/README.md) を読みましたか？"
      options:
        - label: Yes, it have.
          required: true

  - type: checkboxes
    id: was-your-bug-report-not-in-issue
    attributes:
      label: Was your bug report not in Issue?
      description: "[Issue](https://github.com/aonekoaoi/aonekoaoi.github.io/labels/Type%3A%20Bug%20%2F%20%E3%82%BF%E3%82%A4%E3%83%97%EF%BC%9A%E3%83%90%E3%82%B0) に同じ内容の投稿はありませんでしたか？"
      options:
        - label: Yes, it was.
          required: true

  - type: textarea
    id: development-environment
    attributes:
      label: Development Environment
      description: 開発環境または動作環境を詳しく記載してください。
      value: "- \n- \n- \n...\n"
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: バグの概要を詳しく記載してください。スクリーンショットまたは動画等でも可能です。
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: バグを再現させる手順を詳しく記載してください。スクリーンショットまたは動画等でも可能です。
      value: "1. \n2. \n3. \n...\n"
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: 追加の補足等があれば記載してください。
